package ru.entel.web.hib_entity;
// Generated 31.07.2015 11:26:18 by Hibernate Tools 4.3.1



/**
 * Properties generated by hbm2java
 */
public class Properties  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String value;
     private String desc;

    public Properties() {
    }

    public Properties(String name, String value, String desc) {
       this.name = name;
       this.value = value;
       this.desc = desc;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    public String getDesc() {
        return this.desc;
    }
    
    public void setDesc(String desc) {
        this.desc = desc;
    }




}


